import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://practicesoftwaretesting.com/")
    page.get_by_test_id("nav-sign-in").click()
    page.get_by_test_id("register-link").click()
    page.get_by_test_id("first-name").click()
    page.get_by_test_id("first-name").fill("Pranay")
    page.get_by_test_id("first-name").press("Tab")
    page.get_by_test_id("last-name").fill("V")
    page.get_by_test_id("dob").click()
    page.get_by_test_id("dob").fill("1996-08-09")
    page.get_by_test_id("country").select_option("IN")
    page.get_by_test_id("postal_code").click()
    page.get_by_test_id("postal_code").fill("442308")
    page.get_by_test_id("house_number").click()
    page.get_by_test_id("house_number").fill("56")
    page.get_by_test_id("street").click()
    page.get_by_test_id("street").fill("Elody House Street 5")
    page.get_by_test_id("city").click()
    page.get_by_test_id("state").click()
    page.get_by_test_id("phone").click()
    page.get_by_test_id("phone").fill("9998887770")
    page.get_by_test_id("email").click()
    page.get_by_test_id("email").fill("vighnepranay247@gmail.com")
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("qweqwe@123")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").press("ArrowLeft")
    page.get_by_test_id("password").fill("asdqweqwe@123")
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("Qweqwe@12")
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("register-form").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_test_id("password").click(click_count=3)
    page.get_by_test_id("password").fill("Dontaskme@1234")
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("Dontaskme@123455")
    page.get_by_test_id("register-submit").click()
    page.get_by_test_id("email").click()
    page.get_by_test_id("email").fill("vighnepranay247@gmail.com")
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("Dontaskme@123455")
    page.get_by_test_id("login-form").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_test_id("login-submit").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
